name: acumacum
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+8

environment:
  sdk: ">=3.4.0-282.1.beta <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  firebase_core: 3.3.0
  firebase_analytics: 11.2.1
  cloud_firestore: 5.2.0
  firebase_auth: 5.1.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  geolocator: ^12.0.0
  image_picker: ^1.0.7
  image_picker_android: ^0.8.9+3
  image_picker_ios: ^0.8.9+3
  firebase_storage: 12.1.2
  path: ^1.9.0
  archive:
  easy_pdf_viewer: ^1.0.8
  firebase_messaging: 15.0.4
  flutter_local_notifications: ^17.0.0
  bubble_bottom_bar: ^2.0.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.8
  cached_network_image: ^3.3.1
  video_player: ^2.8.5
  flutter_cache_manager: ^3.3.1
  font_awesome_flutter: ^9.0.0
  photo_view: ^0.15.0
  fl_geocoder: ^0.1.0+1
  direct_select: ^2.0.0
  direct_select_flutter: ^1.1.1
  timeago: ^3.6.1
  sliding_up_panel: ^2.0.0+1
  rflutter_alert: ^2.0.7
  url_launcher: ^6.2.5
  expandable: ^5.0.1
  share_plus: ^10.0.0
  firebase_dynamic_links: ^6.0.4
  algolia: ^1.1.2
  time_range_picker: any
  syncfusion_localizations: ^26.2.7
  translator: ^1.0.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  progress_dialog_null_safe: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  logger: ^2.2.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.0.1
  cupertino_icons: ^1.0.6
  rive: ^0.13.9
  widget_and_text_animator: ^1.1.5
  animated_text_kit: ^4.2.2
  multi_select_flutter: ^4.1.3
  table_calendar: ^3.0.9
  intl: ^0.19.0
  geocoding: ^3.0.0
  add_2_calendar: ^3.0.1
  flutter_stripe: ^11.3.0
  liquid_pull_to_refresh: ^3.0.0
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^26.2.14
  tflite_flutter: ^0.11.0
  cloud_functions: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"

dependency_overrides:
  http: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  # fonts:
  #   - asset: assets/fonts/Marg.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
